// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(DbContextRepository))]
    partial class DbContextRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Article", b =>
                {
                    b.Property<int>("IdArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArticle"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdArticle");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            IdArticle = 1,
                            Author = "John Doe",
                            Tag = "Programming",
                            Title = "Introduction to C#",
                            Year = 2021
                        },
                        new
                        {
                            IdArticle = 2,
                            Author = "Jane Smith",
                            Tag = "Programming",
                            Title = "Advanced C# Techniques",
                            Year = 2022
                        },
                        new
                        {
                            IdArticle = 3,
                            Author = "Alice Johnson",
                            Tag = "Database",
                            Title = "Entity Framework Core",
                            Year = 2021
                        },
                        new
                        {
                            IdArticle = 4,
                            Author = "Bob Brown",
                            Tag = "Web Development",
                            Title = "ASP.NET Core Basics",
                            Year = 2020
                        },
                        new
                        {
                            IdArticle = 5,
                            Author = "Charlie Davis",
                            Tag = "Programming",
                            Title = "LINQ Fundamentals",
                            Year = 2019
                        },
                        new
                        {
                            IdArticle = 6,
                            Author = "Diana Evans",
                            Tag = "Web Development",
                            Title = "Blazor for Beginners",
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
